# 1.vim ingress.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: shf-id-generator-server
  namespace: dev
spec:
  rules:
    - host: www.hyfetech.com
      http:
        paths:
          - path: /shf-id-generator-server
            backend:
              serviceName: shf-id-generator-server
              servicePort: 9192